### ISSUE TITLE
Error in UseMethod("filter") :    no applicable method for 'filter' applied to an object of class "c('double', 'numeric')"

### ISSUE THREAD

**Issue by lulumagic7** [HuntsmanCancerInstitute/hciR#1]
Hey,

I tried to use function **write_gsea_rnk(res)** to get my GSEA ranked list. but I got an error in UseMethod("filter") :    no applicable method for 'filter' applied to an object of class "c('double', 'numeric')". Here is my script:

```{r}
sampleNames <- c("GluC31","Glu237","GluU1_4","GluU2_2","GluU3_9","GluU4_3","GluU6_3","Glu229","Glu230","GluF1_6","GluF2_6","GluF3_3","GluF5_3")
data <- read.table("D:/experiment/data analysis/fxs project/FXS btach2 glu 13 samples 202206/new/featurecounts/counts.txt", header = TRUE, quote = "\t", skip = 1)
names(data)[7:19] <- sampleNames
countData <- as.matrix(data[7:19])
rownames(countData) <- data$Geneid
database <- data.frame(name=sampleNames, condition=c("control","control","control","control","control","control","control","FXS","FXS","FXS","FXS","FXS","FXS"))
rownames(database) <- sampleNames
```

```{r}
dds <- DESeqDataSetFromMatrix(countData, colData=database, design= ~ condition)
dds <- dds[ rowSums(counts(dds)) >= 10, ]
dds <- DESeq(dds)
```

```{r}
res <- results(dds)
res <- res[!is.na(res$log2FoldChange),]
```

```{r}
gsea <- write_gsea_rnk(res)
```

Could you please help me?

Best,

Lu

**Comment by cstubben** [comment]
Hi Lu, sorry I should fix that to check for valid input.  Write_gsea_rnk typically uses a list of tibbles from results_all as input.   You can convert your DataFrame to a tibble and then run the function
`write_gsea_rnk( as_tibble(res, rownames="gene_name"), file="FXS_vs_ctrl.rnk")`

**Comment by lulumagic7** [comment]
hey,

Thanks so much for your help! how could I input this "FXS_VS_ctrl.rnk" file into GSEA analysis?

Best,

Lu

**Comment by cstubben** [comment]
You can use that file as input to Broad's GSEA program at https://www.gsea-msigdb.org/gsea/index.jsp
Or you can follow the code in https://github.com/HuntsmanCancerInstitute/hciR/blob/master/vignettes/Liver.md#gsea to run fgsea.   fgsea_all also uses a list of tibbles from results_all as input, but you can probably convert your results with `res2 <- as_tibble(res, rownames="gene_name")`

**Comment by lulumagic7** [comment]
got you, thanks so much!

**Comment by lulumagic7** [comment]
hey,

I ran the code:

**res2 <- as_tibble(res, rownames="gene_name")
k1 <- fgsea_all(res2, msig_pathways$KEGG)**

but I got an error:
**Error in fgsea_all(res2, msig_pathways$KEGG) : Missing contrast name**

is there something I missed?
